use std::path::Path;

use crate::error::InitError;
use crate::state::{ArtifactIntent, InitPhase, InitState, RequirementSource};

const MAX_LINES: usize = 300;

pub fn build_artifacts(
    project_dir: &Path,
    session_id: &str,
    state: &InitState,
) -> Result<Vec<String>, InitError> {
    let artifacts_dir = project_dir
        .join(".orquestra")
        .join("init")
        .join(session_id)
        .join("artifacts");
    std::fs::create_dir_all(&artifacts_dir)?;

    let intent = state
        .classification
        .as_ref()
        .map(|c| c.intent)
        .unwrap_or(ArtifactIntent::Build);

    let mut files = Vec::new();

    let main_content = generate_main_artifact(intent, session_id, state);
    let main_path = artifacts_dir.join("README.md");
    let main_safe = enforce_conciseness(&main_content, "README.md", &artifacts_dir);
    std::fs::write(&main_path, &main_safe)?;
    files.push("artifacts/README.md".to_string());

    let detail = generate_detail_artifact(intent, session_id, state);
    let detail_path = artifacts_dir.join("SPEC.md");
    let detail_safe = enforce_conciseness(&detail, "SPEC.md", &artifacts_dir);
    std::fs::write(&detail_path, &detail_safe)?;
    files.push("artifacts/SPEC.md".to_string());

    Ok(files)
}

fn generate_main_artifact(
    _intent: ArtifactIntent,
    init_session_id: &str,
    state: &InitState,
) -> String {
    let idea = &state.idea;
    let reqs = &state.requirements.items;
    let draft = state.plan_draft.as_ref();

    let mut out = String::new();
    out.push_str(&format!(
        "# {}\n\n",
        draft
            .map(|d| d.title.clone())
            .unwrap_or_else(|| idea.clone())
    ));
    out.push_str("> Generated by `orquestra init`\n\n");
    out.push_str(&format!("**Init session:** `{init_session_id}`\n\n"));
    if let InitPhase::Applied { session_id } = &state.phase {
        out.push_str(&format!("**Runtime session:** `{session_id}`\n\n"));
    }

    out.push_str("## Objective\n\n");
    out.push_str(&format!("{}\n\n", idea));

    out.push_str("## Classification\n\n");
    if let Some(c) = &state.classification {
        out.push_str(&format!(
            "- **Intent:** {:?}\n- **Scope:** {:?}\n- **Audience:** {:?}\n- **Confidence:** {:.2}\n\n",
            c.intent, c.scope, c.audience, c.confidence
        ));
    }

    out.push_str("## Requirements\n\n");
    if reqs.is_empty() {
        out.push_str("_None captured yet._\n\n");
    } else {
        for (i, r) in reqs.iter().enumerate() {
            let source = match r.source {
                RequirementSource::User => "user",
                RequirementSource::Research => "research",
                RequirementSource::Inferred => "inferred",
            };
            out.push_str(&format!("{}. {} _(source: {source})_\n", i + 1, r.text));
        }
        out.push('\n');
    }

    if let Some(d) = draft {
        out.push_str("## Plan\n\n");
        out.push_str(&format!("**Tickets:** {}\n\n", d.tickets.len()));
        for wave in &d.waves {
            out.push_str(&format!("### Wave {}\n\n", wave.wave_number));
            for tid in &wave.ticket_ids {
                if let Some(t) = d.tickets.iter().find(|t| &t.id == tid) {
                    out.push_str(&format!(
                        "- **{} - {}**: {} (skill: `{}`)\n",
                        t.id,
                        t.title,
                        t.objective,
                        t.assigned_skill.as_deref().unwrap_or("unresolved")
                    ));
                }
            }
            out.push('\n');
        }

        if !d.skills_required.is_empty() {
            out.push_str("## Skills Required\n\n");
            for s in &d.skills_required {
                out.push_str(&format!("- `{}`\n", s));
            }
            out.push('\n');
        }
    }

    out
}

fn generate_detail_artifact(
    _intent: ArtifactIntent,
    init_session_id: &str,
    state: &InitState,
) -> String {
    let mut out = String::new();
    out.push_str("# Specification\n\n");

    if let Some(c) = &state.classification {
        out.push_str(&format!(
            "## Classification\n\n- **Intent:** {:?}\n- **Scope:** {:?}\n- **Audience:** {:?}\n- **Confidence:** {:.0}%\n- **Rationale:** {}\n\n",
            c.intent,
            c.scope,
            c.audience,
            c.confidence * 100.0,
            c.reasoning
        ));
    }

    out.push_str("## Research Topics\n\n");
    out.push_str(&format!(
        "Validated reports are stored under `.orquestra/init/{init_session_id}/research/`.\n\n"
    ));

    if let Some(d) = &state.plan_draft {
        if !d.research_validated_topics.is_empty() {
            for topic in &d.research_validated_topics {
                out.push_str(&format!("- [Validated] {topic}\n"));
            }
            out.push('\n');
        }

        out.push_str("## Plan Governance\n\n");
        out.push_str(&format!(
            "- **Plan ID:** `{}`\n- **Waves:** {}\n- **Open contradictions:** {}\n- **Verification threshold:** 0.95\n- **Required evidence:** `artifact`\n\n",
            d.id,
            d.waves.len(),
            d.contradictions_open
        ));

        if d.contradictions_open > 0 {
            out.push_str("## Open Contradictions\n\n");
            out.push_str(&format!(
                "WARNING: {} unresolved contradictions blocking convergence.\n\n",
                d.contradictions_open
            ));
        }

        out.push_str("## Ticket Details\n\n");
        for t in &d.tickets {
            out.push_str(&format!("### {} - {}\n\n", t.id, t.title));
            out.push_str(&format!("**Objective:** {}\n\n", t.objective));
            out.push_str(&format!("**Wave:** {}\n\n", t.wave));
            out.push_str(&format!(
                "**Assigned skill:** `{}`\n\n",
                t.assigned_skill.as_deref().unwrap_or("unresolved")
            ));
            if !t.acceptance_criteria.is_empty() {
                out.push_str("**Acceptance Criteria:**\n\n");
                for ac in &t.acceptance_criteria {
                    out.push_str(&format!("- [ ] {}\n", ac));
                }
                out.push('\n');
            }
            if !t.blocked_by.is_empty() {
                out.push_str(&format!("**Blocked by:** {}\n\n", t.blocked_by.join(", ")));
            }
            if !t.preferred_capabilities.is_empty() {
                out.push_str(&format!(
                    "**Capabilities:** {}\n\n",
                    t.preferred_capabilities.join(", ")
                ));
            }
        }
    }

    out
}

fn enforce_conciseness(content: &str, name: &str, output_dir: &Path) -> String {
    let lines: Vec<&str> = content.lines().collect();
    if lines.len() <= MAX_LINES {
        return content.to_string();
    }

    let mut split_point = 0;
    for (i, line) in lines.iter().enumerate().skip(1) {
        if line.starts_with("## ") && i > 10 {
            split_point = i;
            break;
        }
    }
    if split_point == 0 {
        split_point = lines.len().min(MAX_LINES);
    }

    let base: Vec<&str> = lines[..split_point].to_vec();
    let rest: Vec<&str> = lines[split_point..].to_vec();

    let mut result = base.join("\n");
    let detail_name = name.replace(".md", "_DETAILS.md");
    result.push_str(&format!(
        "\n\n> Continued in `{}` ({} lines)\n",
        detail_name,
        rest.len()
    ));

    let detail_path = output_dir.join(&detail_name);
    if let Some(parent) = detail_path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let _ = std::fs::write(&detail_path, rest.join("\n"));

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_state() -> InitState {
        let mut state = InitState::new(
            "test-id".into(),
            "opencode".into(),
            "Build a REST API".into(),
        );
        state.requirements.items = vec![crate::state::Requirement {
            id: "r1".into(),
            text: "Handle 10k requests/min".into(),
            source: crate::state::RequirementSource::User,
            answered: false,
        }];
        state.classification = Some(crate::state::Classification {
            intent: crate::state::ArtifactIntent::Migrate,
            scope: crate::state::ArtifactScope::Medium,
            audience: crate::state::Audience::Developer,
            confidence: 0.92,
            reasoning: "test".into(),
            classified_at: chrono::Utc::now(),
        });
        state.plan_draft = Some(crate::state::PlanDraft {
            id: "plan-1".into(),
            title: "Migrate monolith".into(),
            tickets: vec![crate::state::DraftTicket {
                id: "T1".into(),
                title: "Extract service".into(),
                objective: "Extract first bounded context".into(),
                acceptance_criteria: vec!["Service extracted".into()],
                blocked_by: vec![],
                preferred_capabilities: vec!["migration".into()],
                assigned_skill: None,
                research_validated: false,
                wave: 1,
            }],
            waves: vec![crate::state::DraftWave {
                wave_number: 1,
                ticket_ids: vec!["T1".into()],
            }],
            skills_required: vec!["migration".into()],
            skills_brain_required: vec![],
            research_validated_topics: vec![],
            contradictions_open: 0,
            created_at: chrono::Utc::now(),
        });
        state
    }

    #[test]
    fn generates_readme() {
        let state = sample_state();
        let content = generate_main_artifact(ArtifactIntent::Build, "test-id", &state);
        assert!(content.contains("Build a REST API"));
        assert!(content.contains("## Requirements"));
        assert!(content.contains("## Plan"));
    }

    #[test]
    fn generates_spec() {
        let state = sample_state();
        let content = generate_detail_artifact(ArtifactIntent::Build, "test-id", &state);
        assert!(content.contains("Specification"));
    }

    #[test]
    fn conciseness_does_not_split_short_content() {
        let dir = tempfile::tempdir().unwrap();
        let short = "# Hello\n\nShort content.\n";
        let result = enforce_conciseness(short, "test.md", dir.path());
        assert_eq!(result, short);
    }

    #[test]
    fn conciseness_splits_long_content_at_h2() {
        let dir = tempfile::tempdir().unwrap();
        let mut long = "# Title\n\n".to_string();
        for i in 0..400 {
            long.push_str(&format!("Line {}\n", i));
            if i == 50 {
                long.push_str("## Split Here\n\n");
            }
        }
        let result = enforce_conciseness(&long, "test.md", dir.path());
        assert!(result.contains("_DETAILS.md"));
    }

    #[test]
    fn build_artifacts_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let state = sample_state();
        let files = build_artifacts(dir.path(), "test-session", &state).unwrap();
        assert!(files.contains(&"artifacts/README.md".to_string()));
        assert!(files.contains(&"artifacts/SPEC.md".to_string()));
    }

    #[test]
    fn main_artifact_includes_intent() {
        let state = sample_state();
        let content = generate_main_artifact(ArtifactIntent::Migrate, "test-id", &state);
        assert!(content.contains("migrate") || content.contains("Migrate"));
    }
}
